# Generated by Django 3.2.4 on 2021-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('main_stage', models.CharField(choices=[('M', 'Menu'), ('S', 'Search'), ('ST', 'Stage')], max_length=2)),
                ('menu_stage', models.CharField(choices=[('M', 'Menu'), ('S', 'Search'), ('ST', 'Stage')], max_length=2)),
            ],
        ),
    ]
