# Generated by Django 3.2.6 on 2021-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20211104_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_number',
            field=models.IntegerField(),
        ),
    ]
