# Generated by Django 3.2.6 on 2021-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20211104_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
