# Generated by Django 3.2.6 on 2021-11-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_ordertable_transaction_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='ordertable',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='pay_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='payment_status',
            field=models.CharField(choices=[('E', 'Ecocash'), ('USD', 'US Dollar'), ('Card', 'Card or Bank'), ('None', 'None')], default='None', max_length=5),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.company'),
        ),
    ]
