# Generated by Django 3.2.6 on 2021-11-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20211104_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='company_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.company'),
        ),
    ]
