# Generated by Django 3.2.6 on 2021-11-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_shop_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='company_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.company'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='shop_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.shop'),
        ),
    ]
