# Generated by Django 3.2.6 on 2021-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20211204_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='adress',
            field=models.CharField(max_length=100),
        ),
    ]
