# Generated by Django 3.2.6 on 2021-12-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20211204_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.company'),
        ),
    ]
