# Generated by Django 3.2.6 on 2021-12-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20211205_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='delivery_status',
            field=models.CharField(choices=[('W', 'Waiting Delivery'), ('D', 'Delivered'), ('C', 'Collected')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='payment_status',
            field=models.CharField(choices=[('E', 'Ecocash'), ('USD', 'US Dollar'), ('Card', 'Card or Bank'), ('None', 'None')], default='None', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='transaction_number',
            field=models.IntegerField(null=True),
        ),
    ]
