# Generated by Django 3.2.6 on 2021-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20211205_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
